env:
    browser: true
    es2020: true
extends:
    - 'eslint:recommended'
    - 'plugin:react/recommended'
    - 'plugin:@typescript-eslint/eslint-recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:react-hooks/recommended'
    - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 11
    sourceType: module
plugins:
    - react
    - '@typescript-eslint'
rules:
    '@typescript-eslint/explicit-function-return-type': 0
    '@typescript-eslint/explicit-module-boundary-types': 0
settings:
    react:
        version: 'detect'
